// Generated by gencpp from file custom_msgs/Path.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_PATH_H
#define CUSTOM_MSGS_MESSAGE_PATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <custom_msgs/Position.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct Path_
{
  typedef Path_<ContainerAllocator> Type;

  Path_()
    : path()  {
    }
  Path_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::custom_msgs::Position_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::custom_msgs::Position_<ContainerAllocator> >::other >  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::custom_msgs::Path_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::Path_<ContainerAllocator> const> ConstPtr;

}; // struct Path_

typedef ::custom_msgs::Path_<std::allocator<void> > Path;

typedef boost::shared_ptr< ::custom_msgs::Path > PathPtr;
typedef boost::shared_ptr< ::custom_msgs::Path const> PathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::Path_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::Path_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/kem/Desktop/ChalmersKandidat/Kandidat19/catkin_ws_clean/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Path_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Path_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67855529a0e617b9d739d09c3f57b883";
  }

  static const char* value(const ::custom_msgs::Path_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67855529a0e617b9ULL;
  static const uint64_t static_value2 = 0xd739d09c3f57b883ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/Path";
  }

  static const char* value(const ::custom_msgs::Path_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Position[] path\n\
\n\
================================================================================\n\
MSG: custom_msgs/Position\n\
int32 x\n\
int32 y\n\
";
  }

  static const char* value(const ::custom_msgs::Path_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::Path_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Path_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::Path_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::Path_<ContainerAllocator>& v)
  {
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::custom_msgs::Position_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_PATH_H
