// Generated by gencpp from file custom_msgs/RequestPathRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_REQUESTPATHREQUEST_H
#define CUSTOM_MSGS_MESSAGE_REQUESTPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <custom_msgs/TruckState.h>
#include <custom_msgs/Path.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct RequestPathRequest_
{
  typedef RequestPathRequest_<ContainerAllocator> Type;

  RequestPathRequest_()
    : state()
    , goals()  {
    }
  RequestPathRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , goals(_alloc)  {
  (void)_alloc;
    }



   typedef  ::custom_msgs::TruckState_<ContainerAllocator>  _state_type;
  _state_type state;

   typedef  ::custom_msgs::Path_<ContainerAllocator>  _goals_type;
  _goals_type goals;





  typedef boost::shared_ptr< ::custom_msgs::RequestPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::RequestPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RequestPathRequest_

typedef ::custom_msgs::RequestPathRequest_<std::allocator<void> > RequestPathRequest;

typedef boost::shared_ptr< ::custom_msgs::RequestPathRequest > RequestPathRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::RequestPathRequest const> RequestPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::RequestPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::RequestPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/kem/Desktop/ChalmersKandidat/Kandidat19/catkin_ws_clean/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::RequestPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::RequestPathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::RequestPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::RequestPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::RequestPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::RequestPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::RequestPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba6139a6027479ef6115858ad4c9ae34";
  }

  static const char* value(const ::custom_msgs::RequestPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba6139a6027479efULL;
  static const uint64_t static_value2 = 0x6115858ad4c9ae34ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::RequestPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/RequestPathRequest";
  }

  static const char* value(const ::custom_msgs::RequestPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::RequestPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TruckState state\n\
Path goals\n\
\n\
================================================================================\n\
MSG: custom_msgs/TruckState\n\
Position p\n\
float32 theta1\n\
float32 theta2\n\
\n\
================================================================================\n\
MSG: custom_msgs/Position\n\
int32 x\n\
int32 y\n\
\n\
================================================================================\n\
MSG: custom_msgs/Path\n\
Position[] path\n\
";
  }

  static const char* value(const ::custom_msgs::RequestPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::RequestPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.goals);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RequestPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::RequestPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::RequestPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    s << std::endl;
    Printer< ::custom_msgs::TruckState_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
    s << indent << "goals: ";
    s << std::endl;
    Printer< ::custom_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.goals);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_REQUESTPATHREQUEST_H
