// Generated by gencpp from file custom_msgs/RequestPath.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_REQUESTPATH_H
#define CUSTOM_MSGS_MESSAGE_REQUESTPATH_H

#include <ros/service_traits.h>


#include <custom_msgs/RequestPathRequest.h>
#include <custom_msgs/RequestPathResponse.h>


namespace custom_msgs
{

struct RequestPath
{

typedef RequestPathRequest Request;
typedef RequestPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestPath
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::RequestPath > {
  static const char* value()
  {
    return "22f3c9ad76f7baef9b992077c4b2173c";
  }

  static const char* value(const ::custom_msgs::RequestPath&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::RequestPath > {
  static const char* value()
  {
    return "custom_msgs/RequestPath";
  }

  static const char* value(const ::custom_msgs::RequestPath&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::RequestPathRequest> should match 
// service_traits::MD5Sum< ::custom_msgs::RequestPath > 
template<>
struct MD5Sum< ::custom_msgs::RequestPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::RequestPath >::value();
  }
  static const char* value(const ::custom_msgs::RequestPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::RequestPathRequest> should match 
// service_traits::DataType< ::custom_msgs::RequestPath > 
template<>
struct DataType< ::custom_msgs::RequestPathRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::RequestPath >::value();
  }
  static const char* value(const ::custom_msgs::RequestPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::RequestPathResponse> should match 
// service_traits::MD5Sum< ::custom_msgs::RequestPath > 
template<>
struct MD5Sum< ::custom_msgs::RequestPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::RequestPath >::value();
  }
  static const char* value(const ::custom_msgs::RequestPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::RequestPathResponse> should match 
// service_traits::DataType< ::custom_msgs::RequestPath > 
template<>
struct DataType< ::custom_msgs::RequestPathResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::RequestPath >::value();
  }
  static const char* value(const ::custom_msgs::RequestPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_REQUESTPATH_H
