// Generated by gencpp from file custom_msgs/V2I.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_V2I_H
#define CUSTOM_MSGS_MESSAGE_V2I_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <custom_msgs/Intersection_Action.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct V2I_
{
  typedef V2I_<ContainerAllocator> Type;

  V2I_()
    : intersection()
    , initial_direction()
    , action()  {
    }
  V2I_(const ContainerAllocator& _alloc)
    : intersection(_alloc)
    , initial_direction(_alloc)
    , action(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _intersection_type;
  _intersection_type intersection;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _initial_direction_type;
  _initial_direction_type initial_direction;

   typedef  ::custom_msgs::Intersection_Action_<ContainerAllocator>  _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::custom_msgs::V2I_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::V2I_<ContainerAllocator> const> ConstPtr;

}; // struct V2I_

typedef ::custom_msgs::V2I_<std::allocator<void> > V2I;

typedef boost::shared_ptr< ::custom_msgs::V2I > V2IPtr;
typedef boost::shared_ptr< ::custom_msgs::V2I const> V2IConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::V2I_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::V2I_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/kem/Desktop/ChalmersKandidat/Kandidat19/catkin_ws_clean/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::V2I_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::V2I_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::V2I_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::V2I_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::V2I_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::V2I_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::V2I_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc3e455ff79d1a6a9b04e7b88a16da30";
  }

  static const char* value(const ::custom_msgs::V2I_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc3e455ff79d1a6aULL;
  static const uint64_t static_value2 = 0x9b04e7b88a16da30ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::V2I_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/V2I";
  }

  static const char* value(const ::custom_msgs::V2I_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::V2I_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string intersection\n\
string initial_direction\n\
Intersection_Action action\n\
\n\
================================================================================\n\
MSG: custom_msgs/Intersection_Action\n\
string Intersection_1\n\
string Intersection_2\n\
string Intersection_3\n\
string Roundabout\n\
";
  }

  static const char* value(const ::custom_msgs::V2I_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::V2I_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.intersection);
      stream.next(m.initial_direction);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct V2I_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::V2I_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::V2I_<ContainerAllocator>& v)
  {
    s << indent << "intersection: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.intersection);
    s << indent << "initial_direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.initial_direction);
    s << indent << "action: ";
    s << std::endl;
    Printer< ::custom_msgs::Intersection_Action_<ContainerAllocator> >::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_V2I_H
